// web-svelte/src/lib/features/settings/About.svelte
<script lang="ts">
	import Checkbox from "$lib/components/ui/Checkbox.svelte";

	interface Props {
		version?: string;
		frontendVersion?: string;
		checkUpdateUrl?: string;
		showUpdateIfAvailable?: boolean;
		alsoCheckBetaRelease?: boolean;
	}

	let {
		version = "1.5.0",
		frontendVersion = "1.5.0",
		checkUpdateUrl = "https://github.com/louislam/dockge/releases",
		showUpdateIfAvailable = $bindable(true),
		alsoCheckBetaRelease = $bindable(false),
	}: Props = $props();
</script>

<div class="flex flex-col items-center gap-4 py-6">
	<img src="/icon.svg" alt="Dockge logo" style="width: 160px; height: 160px;" />

	<div class="flex flex-col items-center gap-1">
		<h2 class="text-2xl font-bold text-(--color-font-body) dark:text-(--color-font-dark)">Dockge</h2>
		<p class="text-base text-(--color-font-body) dark:text-(--color-font-dark)">Version: {version}</p>
		<p class="text-base text-gray-400">Frontend Version: {frontendVersion}</p>
	</div>

	<a
		href={checkUpdateUrl}
		target="_blank"
		rel="noopener noreferrer"
		class="text-base text-(--color-font-body) underline dark:text-(--color-font-dark)"
	>
		Check Update On GitHub
	</a>

	<div class="flex flex-col gap-2">
		<Checkbox bind:checked={showUpdateIfAvailable} label="Show update if available" />
		<Checkbox bind:checked={alsoCheckBetaRelease} label="Also check beta release" />
	</div>
</div>

// frontend/src/components/settings/About.vue
<template>
    <div class="d-flex justify-content-center align-items-center">
        <div class="logo d-flex flex-column justify-content-center align-items-center">
            <object class="my-4" width="200" height="200" data="/icon.svg" />
            <div class="fs-4 fw-bold">Dockge</div>
            <div>{{ $t("Version") }}: {{ info.version }}</div>
            <div class="frontend-version">{{ $t("Frontend Version") }}: {{ frontendVersion }}</div>

            <div v-if="!isFrontendBackendVersionMatched" class="alert alert-warning mt-4" role="alert">
                ⚠️ {{ $t("Frontend Version do not match backend version!") }}
            </div>

            <div class="my-3 update-link"><a href="https://github.com/louislam/dockge/releases" target="_blank" rel="noopener">{{ $t("Check Update On GitHub") }}</a></div>

            <div class="mt-1">
                <div class="form-check">
                    <label><input v-model="settings.checkUpdate" type="checkbox" @change="saveSettings()" /> {{ $t("Show update if available") }}</label>
                </div>

                <div class="form-check">
                    <label><input v-model="settings.checkBeta" type="checkbox" :disabled="!settings.checkUpdate" @change="saveSettings()" /> {{ $t("Also check beta release") }}</label>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { inject, type Ref } from "vue";
import { useSocket } from "../../composables/useSocket";

const settings = inject<Ref<Record<string, any>>>("settings")!;
const saveSettings = inject<(callback?: () => void, currentPassword?: string) => void>("saveSettings")!;
const settingsLoaded = inject<Ref<boolean>>("settingsLoaded")!;

const { info, frontendVersion, isFrontendBackendVersionMatched } = useSocket();
</script>

<style lang="scss" scoped>
.logo {
    margin: 4em 1em;
}

.update-link {
    font-size: 0.8em;
}

.frontend-version {
    font-size: 0.9em;
    color: #cccccc;

    .dark & {
        color: #333333;
    }
}

</style>
